name: "Java Cleanup with Eclipse JDT (Headless)"
description: "Runs Eclipse JDT cleanup rules using a headless refactoring engine"
author: "nbauma109"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  project-root:
    description: "Root directory of the Java project to clean"
    required: true
  source-level:
    description: "Java source level (e.g. 21)"
    required: true
  extra-classpath:
    description: "Additional classpath entries (optional)"
    required: false
    default: ""

  # All the cleanup.* options…
  cleanup.array_with_curly:                 { default: "false" }
  cleanup.use_autoboxing:                   { default: "false" }
  cleanup.overridden_assignment_move_decl:  { default: "false" }
  cleanup.always_use_this_for_non_static_method_access: { default: "false" }
  cleanup.remove_trailing_whitespaces_ignore_empty: { default: "false" }
  cleanup.system_property_javaspecversion:  { default: "false" }
  cleanup.primitive_comparison:             { default: "false" }
  cleanup.system_property_file_encoding:    { default: "false" }
  cleanup.format_source_code_changes_only:  { default: "false" }
  cleanup.remove_redundant_semicolons:      { default: "false" }
  cleanup.useless_continue:                 { default: "false" }
  cleanup.qualify_static_member_accesses_through_subtypes_with_declaring_class: { default: "false" }
  cleanup.remove_redundant_type_arguments:  { default: "false" }
  cleanup.remove_unused_imports:            { default: "false" }
  cleanup.break_loop:                       { default: "false" }
  cleanup.pull_up_assignment:               { default: "false" }
  cleanup.stringbuilder:                    { default: "false" }
  cleanup.arrays_fill:                      { default: "false" }
  cleanup.no_super:                         { default: "false" }
  cleanup.use_lambda:                       { default: "false" }
  cleanup.operand_factorization:            { default: "false" }
  cleanup.simplify_lambda_expression_and_method_ref: { default: "false" }
  cleanup.always_use_blocks:                { default: "false" }
  cleanup.stringconcat_to_textblock:        { default: "false" }
  cleanup.sort_members_all:                 { default: "false" }
  cleanup.system_property_path_separator:   { default: "false" }
  cleanup.instanceof:                       { default: "false" }
  cleanup.precompile_regex:                 { default: "false" }
  cleanup.add_missing_annotations:          { default: "false" }
  cleanup.always_use_this_for_non_static_field_access: { default: "false" }
  cleanup.boolean_literal:                  { default: "false" }
  cleanup.sort_members:                     { default: "false" }
  cleanup.always_use_parentheses_in_expressions: { default: "false" }
  cleanup.remove_unused_method_parameters:  { default: "false" }
  cleanup.remove_unused_local_variables:    { default: "false" }
  cleanup.add_missing_deprecated_annotations: { default: "false" }
  cleanup.no_string_creation:               { default: "false" }
  cleanup.use_unboxing:                     { default: "false" }
  cleanup.use_blocks_only_for_return_and_throw: { default: "false" }
  cleanup.standard_comparison:              { default: "false" }
  cleanup.if_condition:                     { default: "false" }
  cleanup.system_property_line_separator:   { default: "false" }
  cleanup.remove_trailing_whitespaces:      { default: "false" }
  cleanup.map_cloning:                      { default: "false" }
  cleanup.add_serial_version_id:            { default: "false" }
  cleanup.try_with_resource:                { default: "false" }
  cleanup.use_this_for_non_static_method_access: { default: "false" }
  cleanup.use_this_for_non_static_method_access_only_if_necessary: { default: "false" }
  cleanup.single_used_field:                { default: "false" }
  cleanup.reduce_indentation:               { default: "false" }
  cleanup.primitive_parsing:                { default: "false" }
  cleanup.make_local_variable_final:        { default: "false" }
  cleanup.qualify_static_member_accesses_with_declaring_class: { default: "false" }
  cleanup.add_missing_override_annotations: { default: "false" }
  cleanup.use_blocks:                       { default: "false" }
  cleanup.multi_catch:                      { default: "false" }
  cleanup.collection_cloning:               { default: "false" }
  cleanup.pull_out_if_from_if_else:         { default: "false" }
  cleanup.make_variable_declarations_final: { default: "false" }
  cleanup.convert_to_enhanced_for_loop_if_loop_var_used: { default: "false" }
  cleanup.redundant_comparator:             { default: "false" }
  cleanup.remove_unused_private_types:      { default: "false" }
  cleanup.system_property_boolean:          { default: "false" }
  cleanup.qualify_static_method_accesses_with_declaring_class: { default: "false" }
  cleanup.lazy_logical_operator:            { default: "false" }
  cleanup.bitwise_conditional_expression:   { default: "false" }
  cleanup.simplify_boolean_if_else:         { default: "false" }
  cleanup.add_all:                          { default: "false" }
  cleanup.use_directly_map_method:          { default: "false" }
  cleanup.system_property_file_separator:   { default: "false" }
  cleanup.qualify_static_field_accesses_with_declaring_class: { default: "false" }
  cleanup.add_generated_serial_version_id:  { default: "false" }
  cleanup.stringbuilder_for_local_vars:     { default: "false" }
  cleanup.controlflow_merge:                { default: "false" }
  cleanup.comparing_on_criteria:            { default: "false" }
  cleanup.do_while_rather_than_while:       { default: "false" }
  cleanup.primitive_serialization:          { default: "false" }
  cleanup.stringbuffer_to_stringbuilder:    { default: "false" }
  cleanup.extract_increment:                { default: "false" }
  cleanup.comparison_statement:             { default: "false" }
  cleanup.insert_inferred_type_arguments:   { default: "false" }
  cleanup.make_private_fields_final:        { default: "false" }
  cleanup.remove_unnecessary_suppress_warnings: { default: "false" }
  cleanup.useless_return:                   { default: "false" }
  cleanup.instanceof_keyword:               { default: "false" }
  cleanup.use_this_for_non_static_field_access_only_if_necessary: { default: "false" }
  cleanup.one_if_rather_than_duplicate_blocks_that_fall_through: { default: "false" }
  cleanup.remove_trailing_whitespaces_all:  { default: "false" }
  cleanup.valueof_rather_than_instantiation: { default: "false" }
  cleanup.plain_replacement:                { default: "false" }
  cleanup.remove_unnecessary_array_creation: { default: "false" }
  cleanup.remove_private_constructors:      { default: "false" }
  cleanup.make_parameters_final:            { default: "false" }
  cleanup.substring:                        { default: "false" }
  cleanup.ternary_operator:                 { default: "false" }
  cleanup.replace_deprecated_calls:         { default: "false" }
  cleanup.merge_conditional_blocks:         { default: "false" }
  cleanup.return_expression:                { default: "false" }
  cleanup.system_property:                  { default: "false" }
  cleanup.unlooped_while:                   { default: "false" }
  cleanup.convert_to_enhanced_for_loop:     { default: "false" }
  cleanup.remove_unused_private_fields:     { default: "false" }
  cleanup.never_use_blocks:                 { default: "false" }
  cleanup.remove_redundant_modifiers:       { default: "false" }
  cleanup.unreachable_block:                { default: "false" }
  cleanup.switch:                           { default: "false" }
  cleanup.redundant_falling_through_block_end: { default: "false" }
  cleanup.number_suffix:                    { default: "false" }
  cleanup.also_simplify_lambda:             { default: "false" }
  cleanup.system_property_javaversion:      { default: "false" }
  cleanup.replace_deprecated_fields:        { default: "false" }
  cleanup.remove_unnecessary_nls_tags:      { default: "false" }
  cleanup.convert_to_switch_expressions:    { default: "false" }
  cleanup.use_this_for_non_static_field_access: { default: "false" }
  cleanup.use_string_is_blank:              { default: "false" }
  cleanup.static_inner_class:               { default: "false" }
  cleanup.qualify_static_member_accesses_through_instances_with_declaring_class: { default: "false" }
  cleanup.add_missing_nls_tags:             { default: "false" }
  cleanup.remove_unnecessary_casts:         { default: "false" }
  cleanup.objects_equals:                   { default: "false" }
  cleanup.convert_functional_interfaces:    { default: "false" }
  cleanup.else_if:                          { default: "false" }
  cleanup.format_source_code:               { default: "false" }
  cleanup.boolean_value_rather_than_comparison: { default: "false" }
  cleanup.add_default_serial_version_id:    { default: "false" }
  cleanup.remove_unused_private_methods:    { default: "false" }
  cleanup.make_type_abstract_if_missing_method: { default: "false" }
  cleanup.join:                             { default: "false" }
  cleanup.embedded_if:                      { default: "false" }
  cleanup.use_anonymous_class_creation:     { default: "false" }
  cleanup.invert_equals:                    { default: "false" }
  cleanup.add_missing_override_annotations_interface_methods: { default: "false" }
  cleanup.switch_for_instanceof_pattern:    { default: "false" }
  cleanup.remove_unused_private_members:    { default: "false" }
  cleanup.never_use_parentheses_in_expressions: { default: "false" }
  cleanup.strictly_equal_or_different:      { default: "false" }
  cleanup.push_down_negation:               { default: "false" }
  cleanup.evaluate_nullable:                { default: "false" }
  cleanup.use_parentheses_in_expressions:   { default: "false" }
  cleanup.hash:                             { default: "false" }
  cleanup.stringconcat_stringbuffer_stringbuilder: { default: "false" }
  cleanup.double_negation:                  { default: "false" }
  cleanup.overridden_assignment:            { default: "false" }
  cleanup.primitive_rather_than_wrapper:    { default: "false" }
  cleanup.correct_indentation:              { default: "false" }
  cleanup.use_var:                          { default: "false" }

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.project-root }}
    - ${{ inputs.source-level }}
    - ${{ inputs.extra-classpath }}
    - ${{ inputs.cleanup-options-json }}
